name: Build Kivy Android APK

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      # Explicitly set Android SDK environment variables to where setup-android action installs it
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean Buildozer environment
      # Remove the .buildozer directory to force a fresh build and re-read of buildozer.spec
      run: |
        rm -rf .buildozer
        echo "Cleaned .buildozer directory."

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Kivy/Buildozer often work well with Python 3.9 or 3.10

    - name: Install System Build Tools (Ant, Autotools, Build Essentials)
      # Install these before Buildozer starts its operations to ensure they are available
      run: |
        sudo apt-get update
        sudo apt-get install -y ant autotools-dev build-essential

    - name: Install Python Dependencies (Buildozer, Cython, Setuptools)
      run: |
        pip install buildozer
        pip install cython
        pip install --upgrade setuptools # Ensure setuptools is up-to-date

    - name: Set up Android SDK and NDK (using dedicated action)
      # This action handles the installation of Android SDK components,
      # including the NDK and platform tools, and accepts licenses.
      uses: android-actions/setup-android@v2
      with:
        api-level: 34 # Target Android API 34
        build-tools: 34.0.0 # Match API 34
        ndk: 25.2.9519653 # NDK version to match 25b, compatible with API 34

    - name: Explicitly set ANDROID_NDK_HOME
      # This step ensures that ANDROID_NDK_HOME points to the correct NDK version
      # installed by the setup-android action, overriding any potential conflicts.
      run: |
        echo "ANDROID_NDK_HOME=${{ env.ANDROID_SDK_ROOT }}/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "P4A_API=34" >> $GITHUB_ENV # Reinforce P4A API level

    - name: Add execute permission to main.py (if needed)
      run: chmod +x main.py

    - name: Build Android APK
      run: |
        # Buildozer should now correctly find all required tools based on buildozer.spec settings
        # and the explicitly set environment variables.
        buildozer android debug -v

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FaceAppAttendance-APK
        path: bin/*.apk
