name: Build Kivy Android APK

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      # Explicitly set Android SDK environment variables to where setup-android action installs it
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Kivy/Buildozer often work well with Python 3.9 or 3.10

    - name: Install Buildozer, Cython, and Setuptools
      run: |
        pip install buildozer
        pip install cython
        pip install --upgrade setuptools # Ensure setuptools is up-to-date

    - name: Set up Android SDK and NDK (using dedicated action)
      # This action handles the installation of Android SDK components,
      # including the NDK and platform tools, and accepts licenses.
      uses: android-actions/setup-android@v2
      with:
        api-level: 34 # Target Android API 34
        build-tools: 34.0.0 # Match API 34
        ndk: 21.4.7075529 # This NDK version corresponds to '21b' used in buildozer.spec

    - name: Create symlinks for deprecated SDK tools paths
      # Buildozer often looks for sdkmanager, aidl, and zipalign in the old 'tools/bin' path.
      # This step creates symlinks from the expected old locations to the actual new locations.
      run: |
        mkdir -p "${{ env.ANDROID_SDK_ROOT }}/tools/bin"
        ln -sf "${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin/sdkmanager" "${{ env.ANDROID_SDK_ROOT }}/tools/bin/sdkmanager"
        ln -sf "${{ env.ANDROID_SDK_ROOT }}/build-tools/34.0.0/aidl" "${{ env.ANDROID_SDK_ROOT }}/tools/bin/aidl"
        ln -sf "${{ env.ANDROID_SDK_ROOT }}/build-tools/34.0.0/zipalign" "${{ env.ANDROID_SDK_ROOT }}/tools/bin/zipalign"
        echo "Symlinks created for sdkmanager, aidl, and zipalign."

    - name: Cache Buildozer dependencies
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Add execute permission to main.py (if needed)
      run: chmod +x main.py

    - name: Build Android APK
      run: |
        # Ensure PATH includes the necessary Android SDK tool directories for Buildozer.
        # The symlinks created earlier should now correctly resolve Buildozer's references.
        export PATH="${{ env.ANDROID_SDK_ROOT }}/build-tools/34.0.0:${{ env.ANDROID_SDK_ROOT }}/platform-tools:${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:$PATH"
        buildozer android debug -v

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FaceAppAttendance-APK
        path: bin/*.apk
