name: Build Kivy Android APK

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      # Explicitly set Android SDK environment variables to where setup-android action installs it
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Kivy/Buildozer often work well with Python 3.9 or 3.10

    - name: Install Buildozer and Cython
      run: |
        pip install buildozer
        pip install cython

    - name: Set up Android SDK and NDK (using dedicated action)
      # This action handles the installation of Android SDK components,
      # including the NDK and platform tools, and accepts licenses.
      uses: android-actions/setup-android@v2
      with:
        api-level: 33 # Corresponds to android.target_sdk_version in buildozer.spec
        build-tools: 33.0.0
        ndk: 21.4.7075529 # This NDK version corresponds to '21b' used in buildozer.spec

    - name: Cache Buildozer dependencies
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Add execute permission to main.py (if needed)
      run: chmod +x main.py

    - name: Build Android APK
      run: |
        # Ensure ANDROID_HOME and ANDROID_SDK_ROOT are set for Buildozer
        # Also, explicitly add the build-tools and platform-tools directories to the PATH environment variable
        export ANDROID_HOME="${{ env.ANDROID_HOME }}"
        export ANDROID_SDK_ROOT="${{ env.ANDROID_SDK_ROOT }}"
        export PATH="${{ env.ANDROID_SDK_ROOT }}/build-tools/33.0.0:${{ env.ANDROID_SDK_ROOT }}/platform-tools:$PATH"
        buildozer android debug -v

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FaceAppAttendance-APK
        path: bin/*.apk
