name: Build APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: System deps
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev ...   # (same as before)

    - name: Python + Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK + NDK 23b           # ⬅️ new
      run: |
        yes | sdkmanager --licenses
        yes | sdkmanager "platform-tools" "platforms;android-33" \
                          "ndk;23.1.7779620" "build-tools;34.0.0"

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: FaceRecognitionApp
        path: bin/*.apk
