name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 23.1.7779620

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool libtool-bin make gcc g++ pkg-config \
            libjpeg-dev zlib1g-dev libfreetype6-dev libpng-dev libblas-dev liblapack-dev \
            ffmpeg openjdk-17-jdk

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Setup Android SDK & NDK
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o tools.zip
          unzip -q tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          rm tools.zip
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-31" "build-tools;33.0.2" "ndk;${NDK_VERSION}"

      - name: Build APK using Buildozer
        run: |
          export ANDROIDSDK=$ANDROID_SDK_ROOT
          export ANDROIDNDK=$ANDROID_SDK_ROOT/ndk/${NDK_VERSION}
          buildozer android debug

      - uses: actions/upload-artifact@v4
        with:
          name: FaceAttendanceAPK
          path: bin/*.apk
