name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install OS dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential git zip unzip libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
          libsqlite3-dev libfreetype6-dev libpng-dev libtiff5-dev libmtdev-dev \
          libgl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libavformat-dev \
          libavcodec-dev libswscale-dev openjdk-17-jdk curl wget

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK and NDK 23b
      run: |
        yes | sdkmanager --licenses
        yes | sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;34.0.0" \
          "ndk;23.1.7779620"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: FaceRecognitionApp-debug
        path: bin/*.apk
